name: ci

on:
  push:
    branches: [main, lab5]
  pull_request:

jobs:
  build-and-test:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: make app

      - name: unit tests
        run: make u_tests
